<div class="search-and-cart">
    <ul>
        <li class="search-icon"><a href="#" ><i class="dripicons-search"></i></a></li>
        <li class="unser-icon"><a href="#"><i class="dripicons-user"></i></a></li>
        <li class="cart-icon"><a href="#"><i class="dripicons-cart"></i></a> <span>2</span></li>
        <li class="active info-bar"><a href="#"><i class="dripicons-vibrate"></i></a></li>
    </ul>
</div>