<div id="zomata-slider" class="slider">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="slider-title">
                    Organic Food Is <br>  Good For Health
                </h1>
                <p class="slider-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                <div class="slider-button">
                    <a href="#">Our Services</a>
                    <a href="#">Our Services</a>
                </div>
            </div>
        </div>
    </div>
</div>