<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="header-text">
                <span><i class="far fa-map"></i>504 White St . Dawsonville, GA 30534 , New York</span>
                <span><i class="far fa-envelope"></i>suport@gmail.com</span>
            </div>
            <div class="header-link">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
                <a href="#"><i class="fab fa-behance"></i></a>
            </div>
        </div>
    </div>
</div>
