<?php
/**
 * Created by PhpStorm.
 * User: phupham
 * Date: 29/03/2019
 * Time: 10:37
 */

namespace TMG\ProductAtb\Block;


use Magento\Catalog\Model\Session;
use Magento\Framework\View\Element\Template;

class Hello extends Template
{
    protected $_template = "hellokitty.phtml";
    protected $_catalogSession;
    protected $_customerSession;
    protected $_checkoutSession;

    public function __construct(
        Template\Context $context,
        Session $catalogSession,
        \Magento\Checkout\Model\Session $checkoutSession,
        \Magento\Customer\Model\Session $customerSession,
        array $data = []
    )
    {
        $this->_catalogSession = $catalogSession;
        $this->_customerSession = $customerSession;
        $this->_checkoutSession = $checkoutSession;
        parent::__construct($context, $data);
    }

    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getCatalogSession()
    {
        return $this->_catalogSession;
    }

    public function getCheckoutSession()
    {
        return $this->_checkoutSession;
    }

    public function getCustomerSession()
    {
        return $this->_customerSession;
    }
}