<section id="advantages">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <img src="" alt="">
            </div>
            <div class="col-md-5">
                <p class="advantages-title">
                    Why Choose Us
                </p>
                <p class="advantages-des">
                    Lorem ipsum dolor sit amet, consectetur adipisicing eliseei ustempor incididunt ut labore et dolore magna aliqua. Ut enim minim veniam quis nostrud exercitation.
                </p>
                <div class="advantages-block">
                    <div class="row">
                        <div class="col-md-3">
                            <img src="" alt="">
                        </div>
                        <div class="col-md-9">
                            <p class="adv-block-title">Natural Process</p>
                            <p class="adv-block-des">Sorem ipsum dolor sit amet consecta dipisicing elit sed do eiusmod tempor incidide.</p>
                        </div>
                    </div>
                </div>
                <div class="advantages-block">
                    <div class="row">
                        <div class="col-md-3">
                            <img src="" alt="">
                        </div>
                        <div class="col-md-9">
                            <p class="adv-block-title">Natural Process</p>
                            <p class="adv-block-des">Sorem ipsum dolor sit amet consecta dipisicing elit sed do eiusmod tempor incidide.</p>
                        </div>
                    </div>
                </div>
                <div class="advantages-block">
                    <div class="row">
                        <div class="col-md-3">
                            <img src="" alt="">
                        </div>
                        <div class="col-md-9">
                            <p class="adv-block-title">Natural Process</p>
                            <p class="adv-block-des">Sorem ipsum dolor sit amet consecta dipisicing elit sed do eiusmod tempor incidide.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>