<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <img src="" alt="">
                <p class="blog-title">
                    Zomata Blog
                </p>
                <p class="blog-des">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmotempor incididunt ut labore et dolore magna aliqua enim minim veniam
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-4">
                <div class="blog-block">
                    <img src="" alt="">
                    <p class="blog-block-title">
                        Monthly Web Development Was Update Just Time Design Variable Fallbacks Zomata.
                    </p>
                    <div class="blog-block-hr"></div>
                    <div class="blog-block-bot">
                        <span><i class="dripicons-user"></i>Kelvin Perales</span>
                        <span><i class="dripicons-calendar"></i>30 Dec 2018</span>
                        <span><i class="dripicons-conversation"></i>(02)</span>
                    </div>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="blog-block">
                    <img src="" alt="">
                    <p class="blog-block-title">
                        Monthly Web Development Was Update Just Time Design Variable Fallbacks Zomata.
                    </p>
                    <div class="blog-block-hr"></div>
                    <div class="blog-block-bot">
                        <span><i class="dripicons-user"></i>Kelvin Perales</span>
                        <span><i class="dripicons-calendar"></i>30 Dec 2018</span>
                        <span><i class="dripicons-conversation"></i>(02)</span>
                    </div>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="blog-block">
                    <img src="" alt="">
                    <p class="blog-block-title">
                        Monthly Web Development Was Update Just Time Design Variable Fallbacks Zomata.
                    </p>
                    <div class="blog-block-hr"></div>
                    <div class="blog-block-bot">
                        <span><i class="dripicons-user"></i>Kelvin Perales</span>
                        <span><i class="dripicons-calendar"></i>30 Dec 2018</span>
                        <span><i class="dripicons-conversation"></i>(02)</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>