<div class="container">
    <section id="brand">
        <div class="row">
            <div class="col-xl-12">
                <div class="brand-img">
                    <img src="" alt="">
                </div>
                <div class="brand-img">
                    <img src="" alt="">
                </div>
                <div class="brand-img">
                    <img src="" alt="">
                </div>
                <div class="brand-img">
                    <img src="" alt="">
                </div>
                <div class="brand-img">
                    <img src="" alt="">
                </div>
                <div class="brand-img">
                    <img src="" alt="">
                </div>
                <div class="brand-img">
                    <img src="" alt="">
                </div>
            </div>
        </div>
    </section>
</div>