<div id="feature" style="background-image: url('<?php echo $this->getViewFileUrl('images/bg/about.png'); ?>')">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="feature-img">
                    <img src="" alt="">
                    <p class="feature-title">
                        Our Features
                    </p>
                    <p class="feature-des">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmotempor incididunt ut labore et dolore magna aliqua enim minim veniam
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="feature-block">
                    <img src="" alt="">
                    <p class="feature-block-title">
                        Natarul Food
                    </p>
                    <p class="feature-block-des">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt ut labore et dolore magna aliqua.
                    </p>
                    <a href="#">Read more <i class="dripicons-arrow-thin-right"></i></a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature-block">
                    <img src="" alt="">
                    <p class="feature-block-title">
                        Biologically Safe

                    </p>
                    <p class="feature-block-des">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt ut labore et dolore magna aliqua.
                    </p>
                    <a href="#">Read more <i class="dripicons-arrow-thin-right"></i></a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature-block">
                    <img src="" alt="">
                    <p class="feature-block-title">
                        Conserve Biodiversity
                    </p>
                    <p class="feature-block-des">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt ut labore et dolore magna aliqua.
                    </p>
                    <a href="#">Read more <i class="dripicons-arrow-thin-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>