<section id="feedback">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-xl-offset-3">
                <img src="" alt="">
                <p class="feedback-title">
                    Zomata Farmer
                </p>
                <p class="feedback-des">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmotempor incididunt ut labore et dolore magna aliqua enim minim veniam
                </p>

            </div>
        </div>
        <div class="row">
            <div class="col-xl-4">
                <div class="feedback-block">
                    <p class="feedback-block-des">
                        Lorem ipsum dolor amet consect etur adipisicing was elit sed do eiusmod tempor incididunt ut labore ethers dolore
                        magna aliqua. Ut enim ad minim veniam feels quis nostrud exercitation ullamco laboris.
                    </p>
                    <div class="feedback-info">
                        <img src="" alt="">
                        <div class="feedback-name">
                            <p class="feedback-info-name">Sileen P. Willilams</p>
                            <span>Web Designer</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>