<section id="gallery">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <img src="" alt="">
                <p class="gallery-title">
                    Zomata Gallery
                </p>
                <p class="gallery-des">Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmotempor incididunt ut labore et dolore magna aliqua enim minim veniam</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
            <div class="col-xl-3 col-lg-3">
                <img src="" alt="">
            </div>
        </div>
    </div>
</section>