<section id="intro">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="" alt="" class="intro-img">
            </div>
            <div class="col-md-6">
                <p class="intro-title">
                    Welcome To <br>  Zomata Organic
                </p>
                <p class="des-medium">
                    with love & dedication
                </p>
                <p class="des-small">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque.
                </p>
                <a href="#">Learn more</a>
            </div>
        </div>
    </div>
</section>