<section id="peoples">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <img src="" alt="">
                <h3 class="peoples-title">
                    Zomata Farmer
                </h3>
                <p class="peoples-des">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmotempor incididunt ut labore et dolore magna aliqua enim minim veniam
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-3">
                <div class="peoples-item">
                    <img src="" alt="">
                    <p class="peoples-item-title">
                        Pablo J. Bleich
                    </p>
                    <p class="peoples-item-des">
                        Organic Farmer
                    </p>
                </div>
            </div>
            <div class="col-xl-3">
                <div class="peoples-item">
                    <img src="" alt="">
                    <p class="peoples-item-title">
                        Louise F. Shows
                    </p>
                    <p class="peoples-item-des">
                        Organic Farmer
                    </p>
                </div>
            </div>
            <div class="col-xl-3">
                <div class="peoples-item">
                    <img src="" alt="">
                    <p class="peoples-item-title">
                        Normand Shannon
                    </p>
                    <p class="peoples-item-des">
                        Organic Farmer
                    </p>
                </div>
            </div>
            <div class="col-xl-3">
                <div class="peoples-item">
                    <img src="" alt="">
                    <p class="peoples-item-title">
                        Renita Gillenwater
                    </p>
                    <p class="peoples-item-des">
                        Organic Farmer
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>