<section id="products">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="products-title">
                    Our Product
                </h3>
                <p class="products-des">Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmotempor incididunt ut labore et dolore magna aliqua enim minim veniam</p>
                <div class="products-nav">
                    <div class="products-tab">
                        <i class="flaticon"></i>
                        <p class="products-tab-name">Vegetables</p>
                        <img src="" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="products-item">
                    <img src="" alt="">
                    <p class="product-item-title">Broccoli Head</p>
                    <div class="products-rating">
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                    </div>
                    <p class="product-item-price">
                        $49.99
                    </p>
                </div>
            </div><div class="col-md-3">
                <div class="products-item">
                    <img src="" alt="">
                    <p class="product-item-title">Broccoli Head</p>
                    <div class="products-rating">
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                    </div>
                    <p class="product-item-price">
                        $49.99
                    </p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="products-item">
                    <img src="" alt="">
                    <p class="product-item-title">Broccoli Head</p>
                    <div class="products-rating">
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                    </div>
                    <p class="product-item-price">
                        $49.99
                    </p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="products-item">
                    <img src="" alt="">
                    <p class="product-item-title">Broccoli Head</p>
                    <div class="products-rating">
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                    </div>
                    <p class="product-item-price">
                        $49.99
                    </p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="products-item">
                    <img src="" alt="">
                    <p class="product-item-title">Broccoli Head</p>
                    <div class="products-rating">
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                        <i class="far fa-star"></i>
                    </div>
                    <p class="product-item-price">
                        $49.99
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>