<section id="visit">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <img src="" alt="">
                <p class="visit-title">
                    Visit Our Zomata Organic
                </p>
                <p class="visit-des">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquie.
                </p>
            </div>
            <div class="col-md-3">
                <a href="" class="visit-button">Visit Now</a>
            </div>
        </div>
    </div>
</section>