<?php //echo $block->getUrl('hello/test'); ?>
<?php //echo $block->getBaseUrl(); ?>
<?php //echo $this->getStoreManagerData(); ?>
<?php //echo $this->getUrlInterfaceData(); ?>

<?php
//    $product_id = 1;
//    $product = $this->getProductById($product_id);
//    $categoryIds = $product->getCategoryIds();
//    var_dump($categoryIds);
//    $categories = $this->getCategoryCollection()->addAttributeToFilter('entity_id', $categoryIds);
//    foreach ( $categories as $item) {
//        echo $item->getName() . "<br>";
//    }
//?>
<?php
//echo $block->getCurrentCurrencySymbol() . '<br />';
//echo $block->getCurrentCurrencyCode() . '<br />';
//echo $block->getBaseCurrencyCode() . '<br />';
//echo $block->getDefaultCurrencyCode() . '<br />';
//echo $block->getCurrentCurrencyRate() . '<br />';
//
//print_r($block->getAvailableCurrencyCodes()) . '<br />';
//print_r($block->getAllowedCurrencies()) . '<br />';

//$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('TMG\ProductAtb\Block\CheckSSL');
// print current product data
//if ($currentProduct = $myBlock->getCurrentProduct()) {
//    echo $currentProduct->getName() . '<br />';
//    echo $currentProduct->getSku() . '<br />';
//    echo $currentProduct->getFinalPrice() . '<br />';
//    echo $currentProduct->getProductUrl() . '<br />';
//    print_r ($currentProduct->getCategoryIds()) . '<br />';
//
//}
//var_dump($this->getCustomerGroups());

?>
