<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <p class="about__welcome">
                    Welcome to my portfolio website!
                </p>
                <p class="about__title">Hey folks, I'm <span>Web Designer</span></p>
                <p class="about__des">
                    Building a successful product is a challenge. I am highly energetic in user experience design, interfaces and web development.
                </p>
                <div class="about__button">
                    <a href="" class="button__download">
                        <i class="uil uil-file-alt"></i>
                        Download Resume
                    </a>
                    <a href="" class="button__quote">
                        Get a free quote
                    </a>
                </div>
            </div>
            <div class="col-md-5">
                <img src="<?php echo $this->getViewFileUrl('images/undraw/undraw_software_engineer_lvl5.svg')?>" alt="" class="about__img"/>
            </div>
        </div>
    </div>
</section>