<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="contact__map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12088.558402180099!2d-73.99373482142036!3d40.75895421922642!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25855b8fb3083%3A0xa0f9aef176042a5c!2sTheater+District%2C+New+York%2C+NY%2C+USA!5e0!3m2!1sen!2smm!4v1549875377188" width="100%" height="295" frameborder="0" style="border:0" allowfullscreen=""></iframe>
                </div>
                <div class="contact__info">
                    <h3 class="contact__info-title">Say hello
                        <span>
                        <a href="#" class="uil uil-dribbble" data-toggle="tooltip" data-placement="left" title="" data-original-title="Dribbble"></a>
                    </span>
                    </h3>
                    <p class="contact__info-text">010 020 0960
                        <span>
                        <a href="#" class="uil uil-instagram" data-toggle="tooltip" data-placement="left" title="" data-original-title="Instagram"></a>
                    </span>
                    </p>
                    <p class="contact__info-text">hello@company.com
                        <span>
                        <a href="#" class="uil uil-youtube" data-toggle="tooltip" data-placement="left" title="" data-original-title="Youtube"></a>
                    </span>
                    </p>
                </div>
            </div>
            <div class="col-md-7">
                <div class="contact__form">
                    <p class="contact__form-title">
                        Interested to work together? Let's talk
                    </p>
                    <input type="text" class="form-control form__input float-left" name="name" placeholder="Your Name">
                    <input type="text" class="form-control form__input float-right" name="name" placeholder="Email">
                    <textarea name="" id="" cols="30" rows="7" class="form_textarea" >Message</textarea>
                    <a href="#" class="contact__send float-right">Send Button</a>
                </div>
            </div>
        </div>
    </div>
</section>