<section id="resume">
    <div class="container">
        <div class="row">
<!--            <div class="row">-->
                <div class="col-md-6">
                    <p class="resume__title">Experiences</p>
                    <div class="resume--vertical">
                        <div class="resume__block">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="resume__year">
                                        <span>2019</span>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="resume__info">
                                        <p class="resume-info-title">Project Manager <span>Best Studio</span></p>
                                        <p class="resume-info-des">
                                            Proin ornare non purus ut rutrum. Nulla facilisi. Aliquam laoreet libero ac pharetra feugiat. Cras ac fermentum nunc, a faucibus nunc.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="resume__block">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="resume__year">
                                        <span>2019</span>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="resume__info">
                                        <p class="resume-info-title">UX Designer <span>Digital Ace</span></p>
                                        <p class="resume-info-des">
                                            Fusce rutrum augue id orci rhoncus molestie. Nunc auctor dignissim lacus vel iaculis.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="resume__block">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="resume__year">
                                        <span>2019</span>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="resume__info">
                                        <p class="resume-info-title">UI Freelancer <span>Best Studio</span></p>
                                        <p class="resume-info-des">
                                            Sed fringilla vitae enim sit amet cursus. Sed cursus dictum tortor quis pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="resume__block">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="resume__year">
                                        <span>2019</span>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="resume__info">
                                        <p class="resume-info-title">Junior Designer <span>Crafted Co.</span></p>
                                        <p class="resume-info-des">
                                            Cras scelerisque scelerisque condimentum. Nullam at volutpat mi. Nunc auctor ipsum eget magna consequat viverra.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <p class="resume__title">Educations</p>
                    <div class="resume--vertical">
                        <div class="resume__block">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="resume__year">
                                        <span>2019</span>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="resume__info">
                                        <p class="resume-info-title">Mobile Web <span>Master Design</span></p>
                                        <p class="resume-info-des">
                                            Please tell your friends about Tooplate website. That would be very helpful. We need your support.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="resume__block">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="resume__year">
                                        <span>2019</span>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="resume__info">
                                        <p class="resume-info-title">User Interfaces <span>Creative Agency</span></p>
                                        <p class="resume-info-des">
                                            Tooplate is a great website to download HTML templates without any login or email.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="resume__block">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="resume__year">
                                        <span>2019</span>
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="resume__info">
                                        <p class="resume-info-title">Artwork Design <span>New Art School</span></p>
                                        <p class="resume-info-des">
                                            You can freely use Tooplate's templates for your business or personal sites. You cannot redistribute this template without a permission.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
<!--            </div>-->
        </div>
    </div>
</section>